/*
 * DayBook Auth API
 * API for authentication in DayBook
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.auth.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.auth.JSON;

/**
 * UserHasRoles
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-26T10:22:59.295027+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class UserHasRoles {
  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @jakarta.annotation.Nullable
  private Integer flags;

  public static final String SERIALIZED_NAME_ROLES = "roles";
  @SerializedName(SERIALIZED_NAME_ROLES)
  @jakarta.annotation.Nullable
  private List<String> roles = new ArrayList<>();

  public static final String SERIALIZED_NAME_USER_NAME = "user_name";
  @SerializedName(SERIALIZED_NAME_USER_NAME)
  @jakarta.annotation.Nullable
  private String userName;

  public static final String SERIALIZED_NAME_VISIBLE = "visible";
  @SerializedName(SERIALIZED_NAME_VISIBLE)
  @jakarta.annotation.Nullable
  private Boolean visible;

  public UserHasRoles() {
  }

  public UserHasRoles flags(@jakarta.annotation.Nullable Integer flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @jakarta.annotation.Nullable
  public Integer getFlags() {
    return flags;
  }

  public void setFlags(@jakarta.annotation.Nullable Integer flags) {
    this.flags = flags;
  }


  public UserHasRoles roles(@jakarta.annotation.Nullable List<String> roles) {
    this.roles = roles;
    return this;
  }

  public UserHasRoles addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

  /**
   * Get roles
   * @return roles
   */
  @jakarta.annotation.Nullable
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(@jakarta.annotation.Nullable List<String> roles) {
    this.roles = roles;
  }


  public UserHasRoles userName(@jakarta.annotation.Nullable String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName
   */
  @jakarta.annotation.Nullable
  public String getUserName() {
    return userName;
  }

  public void setUserName(@jakarta.annotation.Nullable String userName) {
    this.userName = userName;
  }


  public UserHasRoles visible(@jakarta.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Get visible
   * @return visible
   */
  @jakarta.annotation.Nullable
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(@jakarta.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserHasRoles userHasRoles = (UserHasRoles) o;
    return Objects.equals(this.flags, userHasRoles.flags) &&
        Objects.equals(this.roles, userHasRoles.roles) &&
        Objects.equals(this.userName, userHasRoles.userName) &&
        Objects.equals(this.visible, userHasRoles.visible);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flags, roles, userName, visible);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserHasRoles {\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("flags", "roles", "user_name", "visible"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UserHasRoles
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserHasRoles.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UserHasRoles is not found in the empty JSON string", UserHasRoles.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UserHasRoles.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UserHasRoles` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("roles") != null && !jsonObj.get("roles").isJsonNull() && !jsonObj.get("roles").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `roles` to be an array in the JSON string but got `%s`", jsonObj.get("roles").toString()));
      }
      if ((jsonObj.get("user_name") != null && !jsonObj.get("user_name").isJsonNull()) && !jsonObj.get("user_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `user_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserHasRoles.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserHasRoles' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserHasRoles> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserHasRoles.class));

       return (TypeAdapter<T>) new TypeAdapter<UserHasRoles>() {
           @Override
           public void write(JsonWriter out, UserHasRoles value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserHasRoles read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UserHasRoles given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UserHasRoles
   * @throws IOException if the JSON string is invalid with respect to UserHasRoles
   */
  public static UserHasRoles fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserHasRoles.class);
  }

  /**
   * Convert an instance of UserHasRoles to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

