address: 0.0.0.0:8089
advisory_lock_sleep_duration: 60s
auth_cost: 11
dbhost: 127.0.0.1
dbname: db
dboptions: application_name=auth&search_path=auth
dbpassword: password
dbport: 65432
dbuser: dbuser
db_pool_max_conns: 16
db_pool_min_conns: 1
db_pool_max_conn_lifetime: 1h
db_pool_max_conn_idle_time: 47s
db_pool_health_check_period: 43s
debug: false
https: false
hostname: localhost
insecure_skip_verify: false
request_max_bytes: 1048576
scheduler_job_sleep_duration: 5s
valid_period_access_token: 41m0s
valid_period_refresh_token: 17h0m0s
verbose: false