// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_user_attrs.sql

package user_has_roles

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

//go:generate mockgen -destination=db_mock_test.go -package=user_has_roles github.com/vskurikhin/DayBook3/auth/v2/internal/server/repository/user_has_roles DBTX

var _ Repo = (*Queries)(nil)

type Repo interface {
	CreateUserHasRoles(ctx context.Context, arg CreateUserHasRolesParams) (UserHasRole, error)
	DeleteUserHasRolesBy(ctx context.Context, userName string) error
	DeleteUserHasRolesByID(ctx context.Context, id int64) error
	GetRolesForUserName(ctx context.Context, userName string) (GetRolesForUserNameRow, error)
	ListUserHasRoles(ctx context.Context) ([]UserHasRole, error)
	ListUserHasRolesByRole(ctx context.Context, role string) ([]UserHasRole, error)
	ListUserHasRolesByUserName(ctx context.Context, userName string) ([]UserHasRole, error)
	UpdateUserHasRoles(ctx context.Context, arg UpdateUserHasRolesParams) error
	WithTx(tx pgx.Tx) *Queries
}

//go:generate mockgen -destination=rows_mock_test.go -package=user_has_roles github.com/vskurikhin/DayBook3/auth/v2/internal/server/repository/user_has_roles Rows
type Rows interface {
	Close()
	Err() error
	CommandTag() pgconn.CommandTag
	FieldDescriptions() []pgconn.FieldDescription
	Next() bool
	Scan(dest ...any) error
	Values() ([]any, error)
	RawValues() [][]byte
	Conn() *pgx.Conn
}

//go:generate mockgen -destination=row_mock_test.go -package=user_has_roles github.com/vskurikhin/DayBook3/auth/v2/internal/server/repository/user_has_roles Row
type Row interface {
	Scan(dest ...any) error
}
