// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_user_has_roles.sql

package user_has_roles

import (
	"context"
)

const createUserHasRoles = `-- name: CreateUserHasRoles :one
INSERT INTO user_has_roles (
    user_name, role, enabled, local_change
) VALUES (
  $1, $2, true, true
)
RETURNING id, user_name, role, create_time, update_time, enabled, local_change, visible, flags
`

type CreateUserHasRolesParams struct {
	UserName string `json:"user_name"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUserHasRoles(ctx context.Context, arg CreateUserHasRolesParams) (UserHasRole, error) {
	row := q.db.QueryRow(ctx, createUserHasRoles, arg.UserName, arg.Role)
	var i UserHasRole
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Role,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Enabled,
		&i.LocalChange,
		&i.Visible,
		&i.Flags,
	)
	return i, err
}

const deleteUserHasRolesBy = `-- name: DeleteUserHasRolesBy :exec
DELETE FROM user_has_roles
WHERE user_name = $1
`

func (q *Queries) DeleteUserHasRolesBy(ctx context.Context, userName string) error {
	_, err := q.db.Exec(ctx, deleteUserHasRolesBy, userName)
	return err
}

const deleteUserHasRolesByID = `-- name: DeleteUserHasRolesByID :exec
DELETE FROM user_has_roles
WHERE id = $1
`

func (q *Queries) DeleteUserHasRolesByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserHasRolesByID, id)
	return err
}

const getRolesForUserName = `-- name: GetRolesForUserName :one
SELECT user_name, enabled, array_agg(role) AS roles
FROM user_has_roles
WHERE enabled AND user_name = $1
GROUP BY user_name, enabled LIMIT 1
`

type GetRolesForUserNameRow struct {
	UserName string   `json:"user_name"`
	Enabled  bool     `json:"enabled"`
	Roles    []string `json:"roles"`
}

func (q *Queries) GetRolesForUserName(ctx context.Context, userName string) (GetRolesForUserNameRow, error) {
	row := q.db.QueryRow(ctx, getRolesForUserName, userName)
	var i GetRolesForUserNameRow
	err := row.Scan(&i.UserName, &i.Enabled, &i.Roles)
	return i, err
}

const listUserHasRoles = `-- name: ListUserHasRoles :many
SELECT id, user_name, role, create_time, update_time, enabled, local_change, visible, flags FROM user_has_roles
ORDER BY user_name
`

func (q *Queries) ListUserHasRoles(ctx context.Context) ([]UserHasRole, error) {
	rows, err := q.db.Query(ctx, listUserHasRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserHasRole
	for rows.Next() {
		var i UserHasRole
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Role,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Enabled,
			&i.LocalChange,
			&i.Visible,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserHasRolesByRole = `-- name: ListUserHasRolesByRole :many
SELECT id, user_name, role, create_time, update_time, enabled, local_change, visible, flags FROM user_has_roles
WHERE role = $1
`

func (q *Queries) ListUserHasRolesByRole(ctx context.Context, role string) ([]UserHasRole, error) {
	rows, err := q.db.Query(ctx, listUserHasRolesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserHasRole
	for rows.Next() {
		var i UserHasRole
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Role,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Enabled,
			&i.LocalChange,
			&i.Visible,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserHasRolesByUserName = `-- name: ListUserHasRolesByUserName :many
SELECT id, user_name, role, create_time, update_time, enabled, local_change, visible, flags FROM user_has_roles
WHERE user_name = $1
`

func (q *Queries) ListUserHasRolesByUserName(ctx context.Context, userName string) ([]UserHasRole, error) {
	rows, err := q.db.Query(ctx, listUserHasRolesByUserName, userName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserHasRole
	for rows.Next() {
		var i UserHasRole
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Role,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Enabled,
			&i.LocalChange,
			&i.Visible,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserHasRoles = `-- name: UpdateUserHasRoles :exec
UPDATE user_has_roles
  set enabled = $2
WHERE user_name = $1
`

type UpdateUserHasRolesParams struct {
	UserName string `json:"user_name"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) UpdateUserHasRoles(ctx context.Context, arg UpdateUserHasRolesParams) error {
	_, err := q.db.Exec(ctx, updateUserHasRoles, arg.UserName, arg.Enabled)
	return err
}
