// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/internal/server/services (interfaces: TxDelayer)
//
// Generated by this command:
//
//	mockgen -destination=mock_tx_delayer_test.go -package=services github.com/vskurikhin/DayBook3/auth/v2/internal/server/services TxDelayer
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTxDelayer is a mock of TxDelayer interface.
type MockTxDelayer struct {
	ctrl     *gomock.Controller
	recorder *MockTxDelayerMockRecorder
	isgomock struct{}
}

// MockTxDelayerMockRecorder is the mock recorder for MockTxDelayer.
type MockTxDelayerMockRecorder struct {
	mock *MockTxDelayer
}

// NewMockTxDelayer creates a new mock instance.
func NewMockTxDelayer(ctrl *gomock.Controller) *MockTxDelayer {
	mock := &MockTxDelayer{ctrl: ctrl}
	mock.recorder = &MockTxDelayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxDelayer) EXPECT() *MockTxDelayerMockRecorder {
	return m.recorder
}

// Defer mocks base method.
func (m *MockTxDelayer) Defer(ctx context.Context, tx pgx.Tx, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Defer", ctx, tx, err)
}

// Defer indicates an expected call of Defer.
func (mr *MockTxDelayerMockRecorder) Defer(ctx, tx, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Defer", reflect.TypeOf((*MockTxDelayer)(nil).Defer), ctx, tx, err)
}
