/*
 * DayBook 3 API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.api.api;

import su.svn.lib.api.ApiException;
import su.svn.lib.api.models.NewBlobRecord;
import su.svn.lib.api.models.ResourceBlobRecord;
import java.util.UUID;
import su.svn.lib.api.models.UpdateBlobRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlobRecordResourceApi
 */
@Disabled
public class BlobRecordResourceApiTest {

    private final BlobRecordResourceApi api = new BlobRecordResourceApi();

    /**
     * Delete BLOB record
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2RecordBlobIdDeleteTest() throws ApiException {
        UUID id = null;
        api.apiV2RecordBlobIdDelete(id);
        // TODO: test validations
    }

    /**
     * Create BLOB record
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2RecordBlobPostTest() throws ApiException {
        NewBlobRecord newBlobRecord = null;
        ResourceBlobRecord response = api.apiV2RecordBlobPost(newBlobRecord);
        // TODO: test validations
    }

    /**
     * Update BLOB record
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2RecordBlobPutTest() throws ApiException {
        UpdateBlobRecord updateBlobRecord = null;
        ResourceBlobRecord response = api.apiV2RecordBlobPut(updateBlobRecord);
        // TODO: test validations
    }

}
