/*
 * DayBook 3 API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.api.api;

import su.svn.lib.api.ApiException;
import su.svn.lib.api.models.RecordData;
import su.svn.lib.api.models.RecordDataPage;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecordResourceApi
 */
@Disabled
public class RecordResourceApiTest {

    private final RecordResourceApi api = new RecordResourceApi();

    /**
     * Get page with list of records
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2RecordsGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        RecordDataPage response = api.apiV2RecordsGet(page, size);
        // TODO: test validations
    }

    /**
     * Retrieves a single record by its unique identifier
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2RecordsIdGetTest() throws ApiException {
        UUID id = null;
        RecordData response = api.apiV2RecordsIdGet(id);
        // TODO: test validations
    }

}
