/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.api;

import su.svn.lib.core.ApiException;
import su.svn.lib.core.models.ErrorResponse;
import su.svn.lib.core.models.NewBlobRecord;
import su.svn.lib.core.models.ResourceBlobRecord;
import java.util.UUID;
import su.svn.lib.core.models.UpdateBlobRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlobRecordControllerApi
 */
@Disabled
public class BlobRecordControllerApiTest {

    private final BlobRecordControllerApi api = new BlobRecordControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBlobRecordTest() throws ApiException {
        NewBlobRecord newBlobRecord = null;
        ResourceBlobRecord response = api.createBlobRecord(newBlobRecord);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBlobRecordTest() throws ApiException {
        UUID id = null;
        api.deleteBlobRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readBlobRecordTest() throws ApiException {
        UUID id = null;
        ResourceBlobRecord response = api.readBlobRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateBlobRecordTest() throws ApiException {
        UpdateBlobRecord updateBlobRecord = null;
        ResourceBlobRecord response = api.updateBlobRecord(updateBlobRecord);
        // TODO: test validations
    }

}
