/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.api;

import su.svn.lib.core.ApiException;
import su.svn.lib.core.models.ErrorResponse;
import su.svn.lib.core.models.NewMarkdownRecord;
import su.svn.lib.core.models.ResourceMarkdownRecord;
import java.util.UUID;
import su.svn.lib.core.models.UpdateMarkdownRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MarkdownRecordControllerApi
 */
@Disabled
public class MarkdownRecordControllerApiTest {

    private final MarkdownRecordControllerApi api = new MarkdownRecordControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createMarkdownRecordTest() throws ApiException {
        NewMarkdownRecord newMarkdownRecord = null;
        ResourceMarkdownRecord response = api.createMarkdownRecord(newMarkdownRecord);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteMarkdownRecordTest() throws ApiException {
        UUID id = null;
        api.deleteMarkdownRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readMarkdownRecordTest() throws ApiException {
        UUID id = null;
        ResourceMarkdownRecord response = api.readMarkdownRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateMarkdownRecordTest() throws ApiException {
        UpdateMarkdownRecord updateMarkdownRecord = null;
        ResourceMarkdownRecord response = api.updateMarkdownRecord(updateMarkdownRecord);
        // TODO: test validations
    }

}
