/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.api;

import su.svn.lib.core.ApiException;
import su.svn.lib.core.models.ErrorResponse;
import su.svn.lib.core.models.NewSetRecord;
import su.svn.lib.core.models.ResourceSetRecord;
import java.util.UUID;
import su.svn.lib.core.models.UpdateSetRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SetRecordControllerApi
 */
@Disabled
public class SetRecordControllerApiTest {

    private final SetRecordControllerApi api = new SetRecordControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSetRecordTest() throws ApiException {
        NewSetRecord newSetRecord = null;
        ResourceSetRecord response = api.createSetRecord(newSetRecord);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSetRecordTest() throws ApiException {
        UUID id = null;
        api.deleteSetRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readSetRecordTest() throws ApiException {
        UUID id = null;
        ResourceSetRecord response = api.readSetRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSetRecordTest() throws ApiException {
        UpdateSetRecord updateSetRecord = null;
        ResourceSetRecord response = api.updateSetRecord(updateSetRecord);
        // TODO: test validations
    }

}
