/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.api;

import su.svn.lib.core.ApiException;
import su.svn.lib.core.models.ErrorResponse;
import su.svn.lib.core.models.NewVectorRecord;
import su.svn.lib.core.models.ResourceVectorRecord;
import java.util.UUID;
import su.svn.lib.core.models.UpdateVectorRecord;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VectorRecordControllerApi
 */
@Disabled
public class VectorRecordControllerApiTest {

    private final VectorRecordControllerApi api = new VectorRecordControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVectorRecordTest() throws ApiException {
        NewVectorRecord newVectorRecord = null;
        ResourceVectorRecord response = api.createVectorRecord(newVectorRecord);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteVectorRecordTest() throws ApiException {
        UUID id = null;
        api.deleteVectorRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readVectorRecordTest() throws ApiException {
        UUID id = null;
        ResourceVectorRecord response = api.readVectorRecord(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateVectorRecordTest() throws ApiException {
        UpdateVectorRecord updateVectorRecord = null;
        ResourceVectorRecord response = api.updateVectorRecord(updateVectorRecord);
        // TODO: test validations
    }

}
