/*
 * DayBook Auth API
 * API for authentication in DayBook
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.auth.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import su.svn.lib.auth.models.Token;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2AuthPost200Response
 */
public class V2AuthPost200ResponseTest {
    private final V2AuthPost200Response model = new V2AuthPost200Response();

    /**
     * Model tests for V2AuthPost200Response
     */
    @Test
    public void testV2AuthPost200Response() {
        // TODO: test V2AuthPost200Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
