app.api.request-id-header-name=X-Request-ID
app.external-jwt-api-key-prefix=${API_SERVER_AUTH_EXTERNAL_JWT_API_KEY_PREFIX:Bearer}
app.external-jwt-verify-key-hmac=${API_SERVER_JWT_EXTERNAL_VERIFY_KEY_HMAC:cd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc}
app.verify-issuer=${API_SERVER_CORE_VERIFY_ISSUER:cd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc}
# -> base64 -> Y2Q4ZjVmOWYtZTNlOC01NjlmLTg3ZWYtZjAzYzZjZmMyOWJj
application.auth-server-connect-timeout=${API_SERVER_AUTH_SERVER_CONNECT_TIMEOUT:900}
application.auth-server-read-timeout=${API_SERVER_AUTH_SERVER_READ_TIMEOUT:500}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.password=${API_SERVER_DB_PASSWORD:password}
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive.url=${API_SERVER_DB_REACTIVE_URL:vertx-reactive:postgresql://localhost:5432/db?application_name=api&currentSchema=api&loggerLevel=TRACE}
quarkus.datasource.username=${API_SERVER_DB_USERNAME:dbuser}

quarkus.hibernate-orm.blocking=false
quarkus.hibernate-orm.fetch.batch-size=1024
quarkus.hibernate-orm.mapping.format.global=ignore

quarkus.http.access-log.enabled=true
# quarkus.http.access-log.pattern="%t - %a - %r - %s - %Ts"
quarkus.http.auth.propagate-security-identity=true
quarkus.http.host=${API_SERVER_HTTP_HOST:127.0.0.1}
quarkus.http.port=${API_SERVER_HTTP_PORT:8081}

quarkus.jackson.write-dates-as-timestamps=false

quarkus.native.additional-build-args=--initialize-at-run-time=org.hibernate.type.format.jakartajson.JakartaJsonIntegration
# ,--initialize-at-run-time=io.jsonwebtoken.impl.security.Randoms

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %i - [%20.-20t] %-40.40c{2.} : %X{REQUEST_ID} %s%n
quarkus.log.level=INFO

quarkus.rest-client."su.svn.api.repository.client.rest.AuthRolesClient".url=${API_SERVER_AUTH_SERVER_ADDRESS:${remote.auth-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.BlobRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.JsonRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.MarkdownRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.RecordViewClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.SetRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.ValueRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.VectorRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}
quarkus.rest-client."su.svn.api.repository.client.rest.XmlRecordClient".url=${API_SERVER_CORE_SERVER_ADDRESS:${remote.core-server-address}}

mp.jwt.verify.algorithm=HS256
mp.jwt.verify.issuer=${app.verify-issuer}

smallrye.jwt.sign.key=${app.external-jwt-verify-key-hmac}
smallrye.jwt.time-to-live=-1
smallrye.jwt.verify.algorithm=HS256
smallrye.jwt.verify.issuer=${app.verify-issuer}
smallrye.jwt.verify.key=${app.external-jwt-verify-key-hmac}
smallrye.jwt.verify.secretkey=${app.external-jwt-verify-key-hmac}

remote.auth-server-address=http://localhost:64148
remote.core-server-address=http://localhost:8082
