// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/cmd/server/cmd (interfaces: Environments)
//
// Generated by this command:
//
//	mockgen -destination=run_mock_environments_test.go -package=cmd github.com/vskurikhin/DayBook3/auth/v2/cmd/server/cmd Environments
//

// Package cmd is a generated GoMock package.
package cmd

import (
	reflect "reflect"

	env "github.com/vskurikhin/DayBook3/auth/v2/internal/server/env"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvironments is a mock of Environments interface.
type MockEnvironments struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentsMockRecorder
	isgomock struct{}
}

// MockEnvironmentsMockRecorder is the mock recorder for MockEnvironments.
type MockEnvironmentsMockRecorder struct {
	mock *MockEnvironments
}

// NewMockEnvironments creates a new mock instance.
func NewMockEnvironments(ctrl *gomock.Controller) *MockEnvironments {
	mock := &MockEnvironments{ctrl: ctrl}
	mock.recorder = &MockEnvironmentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironments) EXPECT() *MockEnvironmentsMockRecorder {
	return m.recorder
}

// Values mocks base method.
func (m *MockEnvironments) Values() env.Values {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Values")
	ret0, _ := ret[0].(env.Values)
	return ret0
}

// Values indicates an expected call of Values.
func (mr *MockEnvironmentsMockRecorder) Values() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Values", reflect.TypeOf((*MockEnvironments)(nil).Values))
}
