/*
 * This file was last modified at 2026.07.01 22:56 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * PagedModelEntityModelResourceRecordViewEmbedded.java
 * $Id$
 */

/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import su.svn.lib.core.models.EntityModelResourceRecordView;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.core.JSON;

/**
 * PagedModelEntityModelResourceRecordViewEmbedded
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-01T22:38:06.881138+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class PagedModelEntityModelResourceRecordViewEmbedded {
  public static final String SERIALIZED_NAME_RESOURCE_RECORD_VIEW_LIST = "resourceRecordViewList";
  @SerializedName(SERIALIZED_NAME_RESOURCE_RECORD_VIEW_LIST)
  @jakarta.annotation.Nullable
  private List<EntityModelResourceRecordView> resourceRecordViewList = new ArrayList<>();

  public PagedModelEntityModelResourceRecordViewEmbedded() {
  }

  public PagedModelEntityModelResourceRecordViewEmbedded resourceRecordViewList(@jakarta.annotation.Nullable List<EntityModelResourceRecordView> resourceRecordViewList) {
    this.resourceRecordViewList = resourceRecordViewList;
    return this;
  }

  public PagedModelEntityModelResourceRecordViewEmbedded addResourceRecordViewListItem(EntityModelResourceRecordView resourceRecordViewListItem) {
    if (this.resourceRecordViewList == null) {
      this.resourceRecordViewList = new ArrayList<>();
    }
    this.resourceRecordViewList.add(resourceRecordViewListItem);
    return this;
  }

  /**
   * Get resourceRecordViewList
   * @return resourceRecordViewList
   */
  @jakarta.annotation.Nullable
  public List<EntityModelResourceRecordView> getResourceRecordViewList() {
    return resourceRecordViewList;
  }

  public void setResourceRecordViewList(@jakarta.annotation.Nullable List<EntityModelResourceRecordView> resourceRecordViewList) {
    this.resourceRecordViewList = resourceRecordViewList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelEntityModelResourceRecordViewEmbedded pagedModelEntityModelResourceRecordViewEmbedded = (PagedModelEntityModelResourceRecordViewEmbedded) o;
    return Objects.equals(this.resourceRecordViewList, pagedModelEntityModelResourceRecordViewEmbedded.resourceRecordViewList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceRecordViewList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelEntityModelResourceRecordViewEmbedded {\n");
    sb.append("    resourceRecordViewList: ").append(toIndentedString(resourceRecordViewList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("resourceRecordViewList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PagedModelEntityModelResourceRecordViewEmbedded
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PagedModelEntityModelResourceRecordViewEmbedded.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PagedModelEntityModelResourceRecordViewEmbedded is not found in the empty JSON string", PagedModelEntityModelResourceRecordViewEmbedded.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PagedModelEntityModelResourceRecordViewEmbedded.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PagedModelEntityModelResourceRecordViewEmbedded` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("resourceRecordViewList") != null && !jsonObj.get("resourceRecordViewList").isJsonNull()) {
        JsonArray jsonArrayresourceRecordViewList = jsonObj.getAsJsonArray("resourceRecordViewList");
        if (jsonArrayresourceRecordViewList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resourceRecordViewList").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `resourceRecordViewList` to be an array in the JSON string but got `%s`", jsonObj.get("resourceRecordViewList").toString()));
          }

          // validate the optional field `resourceRecordViewList` (array)
          for (int i = 0; i < jsonArrayresourceRecordViewList.size(); i++) {
            EntityModelResourceRecordView.validateJsonElement(jsonArrayresourceRecordViewList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PagedModelEntityModelResourceRecordViewEmbedded.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PagedModelEntityModelResourceRecordViewEmbedded' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PagedModelEntityModelResourceRecordViewEmbedded> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PagedModelEntityModelResourceRecordViewEmbedded.class));

       return (TypeAdapter<T>) new TypeAdapter<PagedModelEntityModelResourceRecordViewEmbedded>() {
           @Override
           public void write(JsonWriter out, PagedModelEntityModelResourceRecordViewEmbedded value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PagedModelEntityModelResourceRecordViewEmbedded read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PagedModelEntityModelResourceRecordViewEmbedded given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PagedModelEntityModelResourceRecordViewEmbedded
   * @throws IOException if the JSON string is invalid with respect to PagedModelEntityModelResourceRecordViewEmbedded
   */
  public static PagedModelEntityModelResourceRecordViewEmbedded fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PagedModelEntityModelResourceRecordViewEmbedded.class);
  }

  /**
   * Convert an instance of PagedModelEntityModelResourceRecordViewEmbedded to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

