/*
 * This file was last modified at 2026.07.01 22:56 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * ResourceRecordViewFilter.java
 * $Id$
 */

/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.core.JSON;

/**
 * ResourceRecordViewFilter
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-01T22:38:06.881138+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class ResourceRecordViewFilter {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @jakarta.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_FROM_TIME = "fromTime";
  @SerializedName(SERIALIZED_NAME_FROM_TIME)
  @jakarta.annotation.Nullable
  private OffsetDateTime fromTime;

  public static final String SERIALIZED_NAME_FROM_DATE = "fromDate";
  @SerializedName(SERIALIZED_NAME_FROM_DATE)
  @jakarta.annotation.Nullable
  private OffsetDateTime fromDate;

  public static final String SERIALIZED_NAME_TO_DATE = "toDate";
  @SerializedName(SERIALIZED_NAME_TO_DATE)
  @jakarta.annotation.Nullable
  private OffsetDateTime toDate;

  public static final String SERIALIZED_NAME_WITH_DISABLED = "withDisabled";
  @SerializedName(SERIALIZED_NAME_WITH_DISABLED)
  @jakarta.annotation.Nullable
  private Boolean withDisabled;

  public ResourceRecordViewFilter() {
  }

  public ResourceRecordViewFilter title(@jakarta.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }


  public ResourceRecordViewFilter fromTime(@jakarta.annotation.Nullable OffsetDateTime fromTime) {
    this.fromTime = fromTime;
    return this;
  }

  /**
   * Get fromTime
   * @return fromTime
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getFromTime() {
    return fromTime;
  }

  public void setFromTime(@jakarta.annotation.Nullable OffsetDateTime fromTime) {
    this.fromTime = fromTime;
  }


  public ResourceRecordViewFilter fromDate(@jakarta.annotation.Nullable OffsetDateTime fromDate) {
    this.fromDate = fromDate;
    return this;
  }

  /**
   * Get fromDate
   * @return fromDate
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getFromDate() {
    return fromDate;
  }

  public void setFromDate(@jakarta.annotation.Nullable OffsetDateTime fromDate) {
    this.fromDate = fromDate;
  }


  public ResourceRecordViewFilter toDate(@jakarta.annotation.Nullable OffsetDateTime toDate) {
    this.toDate = toDate;
    return this;
  }

  /**
   * Get toDate
   * @return toDate
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getToDate() {
    return toDate;
  }

  public void setToDate(@jakarta.annotation.Nullable OffsetDateTime toDate) {
    this.toDate = toDate;
  }


  public ResourceRecordViewFilter withDisabled(@jakarta.annotation.Nullable Boolean withDisabled) {
    this.withDisabled = withDisabled;
    return this;
  }

  /**
   * Get withDisabled
   * @return withDisabled
   */
  @jakarta.annotation.Nullable
  public Boolean getWithDisabled() {
    return withDisabled;
  }

  public void setWithDisabled(@jakarta.annotation.Nullable Boolean withDisabled) {
    this.withDisabled = withDisabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceRecordViewFilter resourceRecordViewFilter = (ResourceRecordViewFilter) o;
    return Objects.equals(this.title, resourceRecordViewFilter.title) &&
        Objects.equals(this.fromTime, resourceRecordViewFilter.fromTime) &&
        Objects.equals(this.fromDate, resourceRecordViewFilter.fromDate) &&
        Objects.equals(this.toDate, resourceRecordViewFilter.toDate) &&
        Objects.equals(this.withDisabled, resourceRecordViewFilter.withDisabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, fromTime, fromDate, toDate, withDisabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceRecordViewFilter {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    fromTime: ").append(toIndentedString(fromTime)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    withDisabled: ").append(toIndentedString(withDisabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("title", "fromTime", "fromDate", "toDate", "withDisabled"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResourceRecordViewFilter
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResourceRecordViewFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ResourceRecordViewFilter is not found in the empty JSON string", ResourceRecordViewFilter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResourceRecordViewFilter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResourceRecordViewFilter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResourceRecordViewFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResourceRecordViewFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResourceRecordViewFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResourceRecordViewFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<ResourceRecordViewFilter>() {
           @Override
           public void write(JsonWriter out, ResourceRecordViewFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResourceRecordViewFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResourceRecordViewFilter given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResourceRecordViewFilter
   * @throws IOException if the JSON string is invalid with respect to ResourceRecordViewFilter
   */
  public static ResourceRecordViewFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResourceRecordViewFilter.class);
  }

  /**
   * Convert an instance of ResourceRecordViewFilter to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

