/*
 * This file was last modified at 2026.07.01 22:56 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * UpdateJsonRecord.java
 * $Id$
 */

/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.core.JSON;

/**
 * UpdateJsonRecord
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-01T22:38:06.881138+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class UpdateJsonRecord {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @jakarta.annotation.Nonnull
  private UUID parentId = UUID.fromString("00000000-0000-0000-0000-000000000000");

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @jakarta.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_A_HREF = "aHref";
  @SerializedName(SERIALIZED_NAME_A_HREF)
  @jakarta.annotation.Nullable
  private String aHref;

  public static final String SERIALIZED_NAME_JSON = "json";
  @SerializedName(SERIALIZED_NAME_JSON)
  @jakarta.annotation.Nonnull
  private Map<String, String> json = new HashMap<>();

  public static final String SERIALIZED_NAME_POST_AT = "postAt";
  @SerializedName(SERIALIZED_NAME_POST_AT)
  @jakarta.annotation.Nullable
  private OffsetDateTime postAt;

  public static final String SERIALIZED_NAME_REFRESH_AT = "refreshAt";
  @SerializedName(SERIALIZED_NAME_REFRESH_AT)
  @jakarta.annotation.Nonnull
  private OffsetDateTime refreshAt;

  public static final String SERIALIZED_NAME_VISIBLE = "visible";
  @SerializedName(SERIALIZED_NAME_VISIBLE)
  @jakarta.annotation.Nullable
  private Boolean visible;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @jakarta.annotation.Nullable
  private Integer flags;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @jakarta.annotation.Nullable
  private Set<String> tags = new LinkedHashSet<>();

  public UpdateJsonRecord() {
  }

  public UpdateJsonRecord id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public UpdateJsonRecord parentId(@jakarta.annotation.Nonnull UUID parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @jakarta.annotation.Nonnull
  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(@jakarta.annotation.Nonnull UUID parentId) {
    this.parentId = parentId;
  }


  public UpdateJsonRecord title(@jakarta.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }


  public UpdateJsonRecord aHref(@jakarta.annotation.Nullable String aHref) {
    this.aHref = aHref;
    return this;
  }

  /**
   * Get aHref
   * @return aHref
   */
  @jakarta.annotation.Nullable
  public String getaHref() {
    return aHref;
  }

  public void setaHref(@jakarta.annotation.Nullable String aHref) {
    this.aHref = aHref;
  }


  public UpdateJsonRecord json(@jakarta.annotation.Nonnull Map<String, String> json) {
    this.json = json;
    return this;
  }

  public UpdateJsonRecord putJsonItem(String key, String jsonItem) {
    if (this.json == null) {
      this.json = new HashMap<>();
    }
    this.json.put(key, jsonItem);
    return this;
  }

  /**
   * Get json
   * @return json
   */
  @jakarta.annotation.Nonnull
  public Map<String, String> getJson() {
    return json;
  }

  public void setJson(@jakarta.annotation.Nonnull Map<String, String> json) {
    this.json = json;
  }


  public UpdateJsonRecord postAt(@jakarta.annotation.Nullable OffsetDateTime postAt) {
    this.postAt = postAt;
    return this;
  }

  /**
   * Get postAt
   * @return postAt
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getPostAt() {
    return postAt;
  }

  public void setPostAt(@jakarta.annotation.Nullable OffsetDateTime postAt) {
    this.postAt = postAt;
  }


  public UpdateJsonRecord refreshAt(@jakarta.annotation.Nonnull OffsetDateTime refreshAt) {
    this.refreshAt = refreshAt;
    return this;
  }

  /**
   * Get refreshAt
   * @return refreshAt
   */
  @jakarta.annotation.Nonnull
  public OffsetDateTime getRefreshAt() {
    return refreshAt;
  }

  public void setRefreshAt(@jakarta.annotation.Nonnull OffsetDateTime refreshAt) {
    this.refreshAt = refreshAt;
  }


  public UpdateJsonRecord visible(@jakarta.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Get visible
   * @return visible
   */
  @jakarta.annotation.Nullable
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(@jakarta.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }


  public UpdateJsonRecord flags(@jakarta.annotation.Nullable Integer flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @jakarta.annotation.Nullable
  public Integer getFlags() {
    return flags;
  }

  public void setFlags(@jakarta.annotation.Nullable Integer flags) {
    this.flags = flags;
  }


  public UpdateJsonRecord tags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = tags;
    return this;
  }

  public UpdateJsonRecord addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new LinkedHashSet<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  public Set<String> getTags() {
    return tags;
  }

  public void setTags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateJsonRecord updateJsonRecord = (UpdateJsonRecord) o;
    return Objects.equals(this.id, updateJsonRecord.id) &&
        Objects.equals(this.parentId, updateJsonRecord.parentId) &&
        Objects.equals(this.title, updateJsonRecord.title) &&
        Objects.equals(this.aHref, updateJsonRecord.aHref) &&
        Objects.equals(this.json, updateJsonRecord.json) &&
        Objects.equals(this.postAt, updateJsonRecord.postAt) &&
        Objects.equals(this.refreshAt, updateJsonRecord.refreshAt) &&
        Objects.equals(this.visible, updateJsonRecord.visible) &&
        Objects.equals(this.flags, updateJsonRecord.flags) &&
        Objects.equals(this.tags, updateJsonRecord.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, title, aHref, json, postAt, refreshAt, visible, flags, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateJsonRecord {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    aHref: ").append(toIndentedString(aHref)).append("\n");
    sb.append("    json: ").append(toIndentedString(json)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    refreshAt: ").append(toIndentedString(refreshAt)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "parentId", "title", "aHref", "json", "postAt", "refreshAt", "visible", "flags", "tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "parentId", "json", "refreshAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateJsonRecord
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateJsonRecord.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateJsonRecord is not found in the empty JSON string", UpdateJsonRecord.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateJsonRecord.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateJsonRecord` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateJsonRecord.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("parentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentId").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("aHref") != null && !jsonObj.get("aHref").isJsonNull()) && !jsonObj.get("aHref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `aHref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aHref").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateJsonRecord.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateJsonRecord' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateJsonRecord> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateJsonRecord.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateJsonRecord>() {
           @Override
           public void write(JsonWriter out, UpdateJsonRecord value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateJsonRecord read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateJsonRecord given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateJsonRecord
   * @throws IOException if the JSON string is invalid with respect to UpdateJsonRecord
   */
  public static UpdateJsonRecord fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateJsonRecord.class);
  }

  /**
   * Convert an instance of UpdateJsonRecord to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

