// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/internal/server/repository/advisory_lock (interfaces: PgxConn)
//
// Generated by this command:
//
//	mockgen -destination=mock_pgx_conn_test.go -package=advisory_lock github.com/vskurikhin/DayBook3/auth/v2/internal/server/repository/advisory_lock PgxConn
//

// Package advisory_lock is a generated GoMock package.
package advisory_lock

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockPgxConn is a mock of PgxConn interface.
type MockPgxConn struct {
	ctrl     *gomock.Controller
	recorder *MockPgxConnMockRecorder
	isgomock struct{}
}

// MockPgxConnMockRecorder is the mock recorder for MockPgxConn.
type MockPgxConnMockRecorder struct {
	mock *MockPgxConn
}

// NewMockPgxConn creates a new mock instance.
func NewMockPgxConn(ctrl *gomock.Controller) *MockPgxConn {
	mock := &MockPgxConn{ctrl: ctrl}
	mock.recorder = &MockPgxConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgxConn) EXPECT() *MockPgxConnMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockPgxConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPgxConnMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPgxConn)(nil).Exec), varargs...)
}

// QueryRow mocks base method.
func (m *MockPgxConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockPgxConnMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockPgxConn)(nil).QueryRow), varargs...)
}
