/*
 * DayBook 3 API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import su.svn.lib.api.models.RecordType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecordData
 */
public class RecordDataTest {
    private final RecordData model = new RecordData();

    /**
     * Model tests for RecordData
     */
    @Test
    public void testRecordData() {
        // TODO: test RecordData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'postAt'
     */
    @Test
    public void postAtTest() {
        // TODO: test postAt
    }

    /**
     * Test the property 'refreshAt'
     */
    @Test
    public void refreshAtTest() {
        // TODO: test refreshAt
    }

    /**
     * Test the property 'visible'
     */
    @Test
    public void visibleTest() {
        // TODO: test visible
    }

    /**
     * Test the property 'flags'
     */
    @Test
    public void flagsTest() {
        // TODO: test flags
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'aHref'
     */
    @Test
    public void aHrefTest() {
        // TODO: test aHref
    }

    /**
     * Test the property 'blob'
     */
    @Test
    public void blobTest() {
        // TODO: test blob
    }

    /**
     * Test the property 'json'
     */
    @Test
    public void jsonTest() {
        // TODO: test json
    }

    /**
     * Test the property 'texts'
     */
    @Test
    public void textsTest() {
        // TODO: test texts
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'html'
     */
    @Test
    public void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'markdown'
     */
    @Test
    public void markdownTest() {
        // TODO: test markdown
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'vector'
     */
    @Test
    public void vectorTest() {
        // TODO: test vector
    }

    /**
     * Test the property 'xml'
     */
    @Test
    public void xmlTest() {
        // TODO: test xml
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
