/*
 * DayBook 3 API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.api.models;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecordType
 */
public class RecordTypeTest {
    /**
     * Model tests for RecordType
     */
    @Test
    public void testRecordType() {
        // TODO: test RecordType
    }

}
