/*
 * This file was last modified at 2026.07.01 22:56 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * NewXmlRecord.java
 * $Id$
 */

/*
 * DayBook 3 API
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.api.JSON;

/**
 * NewXmlRecord
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-01T22:50:32.413868+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class NewXmlRecord {
  public static final String SERIALIZED_NAME_VISIBLE = "visible";
  @SerializedName(SERIALIZED_NAME_VISIBLE)
  @jakarta.annotation.Nullable
  private Boolean visible;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @jakarta.annotation.Nullable
  private Integer flags;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @jakarta.annotation.Nullable
  private UUID parentId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @jakarta.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_A_HREF = "aHref";
  @SerializedName(SERIALIZED_NAME_A_HREF)
  @jakarta.annotation.Nullable
  private String aHref;

  public static final String SERIALIZED_NAME_XML = "xml";
  @SerializedName(SERIALIZED_NAME_XML)
  @jakarta.annotation.Nonnull
  private String xml;

  public static final String SERIALIZED_NAME_POST_AT = "postAt";
  @SerializedName(SERIALIZED_NAME_POST_AT)
  @jakarta.annotation.Nonnull
  private OffsetDateTime postAt;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @jakarta.annotation.Nullable
  private Set<String> tags = new LinkedHashSet<>();

  public NewXmlRecord() {
  }

  public NewXmlRecord visible(@jakarta.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Get visible
   * @return visible
   */
  @jakarta.annotation.Nullable
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(@jakarta.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }


  public NewXmlRecord flags(@jakarta.annotation.Nullable Integer flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @jakarta.annotation.Nullable
  public Integer getFlags() {
    return flags;
  }

  public void setFlags(@jakarta.annotation.Nullable Integer flags) {
    this.flags = flags;
  }


  public NewXmlRecord parentId(@jakarta.annotation.Nullable UUID parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @jakarta.annotation.Nullable
  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(@jakarta.annotation.Nullable UUID parentId) {
    this.parentId = parentId;
  }


  public NewXmlRecord title(@jakarta.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }


  public NewXmlRecord aHref(@jakarta.annotation.Nullable String aHref) {
    this.aHref = aHref;
    return this;
  }

  /**
   * Get aHref
   * @return aHref
   */
  @jakarta.annotation.Nullable
  public String getaHref() {
    return aHref;
  }

  public void setaHref(@jakarta.annotation.Nullable String aHref) {
    this.aHref = aHref;
  }


  public NewXmlRecord xml(@jakarta.annotation.Nonnull String xml) {
    this.xml = xml;
    return this;
  }

  /**
   * Get xml
   * @return xml
   */
  @jakarta.annotation.Nonnull
  public String getXml() {
    return xml;
  }

  public void setXml(@jakarta.annotation.Nonnull String xml) {
    this.xml = xml;
  }


  public NewXmlRecord postAt(@jakarta.annotation.Nonnull OffsetDateTime postAt) {
    this.postAt = postAt;
    return this;
  }

  /**
   * Get postAt
   * @return postAt
   */
  @jakarta.annotation.Nonnull
  public OffsetDateTime getPostAt() {
    return postAt;
  }

  public void setPostAt(@jakarta.annotation.Nonnull OffsetDateTime postAt) {
    this.postAt = postAt;
  }


  public NewXmlRecord tags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = tags;
    return this;
  }

  public NewXmlRecord addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new LinkedHashSet<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  public Set<String> getTags() {
    return tags;
  }

  public void setTags(@jakarta.annotation.Nullable Set<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewXmlRecord newXmlRecord = (NewXmlRecord) o;
    return Objects.equals(this.visible, newXmlRecord.visible) &&
        Objects.equals(this.flags, newXmlRecord.flags) &&
        Objects.equals(this.parentId, newXmlRecord.parentId) &&
        Objects.equals(this.title, newXmlRecord.title) &&
        Objects.equals(this.aHref, newXmlRecord.aHref) &&
        Objects.equals(this.xml, newXmlRecord.xml) &&
        Objects.equals(this.postAt, newXmlRecord.postAt) &&
        Objects.equals(this.tags, newXmlRecord.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visible, flags, parentId, title, aHref, xml, postAt, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewXmlRecord {\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    aHref: ").append(toIndentedString(aHref)).append("\n");
    sb.append("    xml: ").append(toIndentedString(xml)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("visible", "flags", "parentId", "title", "aHref", "xml", "postAt", "tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("xml", "postAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NewXmlRecord
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NewXmlRecord.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in NewXmlRecord is not found in the empty JSON string", NewXmlRecord.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NewXmlRecord.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `NewXmlRecord` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NewXmlRecord.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("parentId") != null && !jsonObj.get("parentId").isJsonNull()) && !jsonObj.get("parentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentId").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("aHref") != null && !jsonObj.get("aHref").isJsonNull()) && !jsonObj.get("aHref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `aHref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aHref").toString()));
      }
      if (!jsonObj.get("xml").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `xml` to be a primitive type in the JSON string but got `%s`", jsonObj.get("xml").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NewXmlRecord.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NewXmlRecord' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NewXmlRecord> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NewXmlRecord.class));

       return (TypeAdapter<T>) new TypeAdapter<NewXmlRecord>() {
           @Override
           public void write(JsonWriter out, NewXmlRecord value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NewXmlRecord read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NewXmlRecord given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NewXmlRecord
   * @throws IOException if the JSON string is invalid with respect to NewXmlRecord
   */
  public static NewXmlRecord fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NewXmlRecord.class);
  }

  /**
   * Convert an instance of NewXmlRecord to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

