// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources (interfaces: LogoutServiceV2)
//
// Generated by this command:
//
//	mockgen -destination=mock_logout_service_v2_test.go -package=resources github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources LogoutServiceV2
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogoutServiceV2 is a mock of LogoutServiceV2 interface.
type MockLogoutServiceV2 struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutServiceV2MockRecorder
	isgomock struct{}
}

// MockLogoutServiceV2MockRecorder is the mock recorder for MockLogoutServiceV2.
type MockLogoutServiceV2MockRecorder struct {
	mock *MockLogoutServiceV2
}

// NewMockLogoutServiceV2 creates a new mock instance.
func NewMockLogoutServiceV2(ctrl *gomock.Controller) *MockLogoutServiceV2 {
	mock := &MockLogoutServiceV2{ctrl: ctrl}
	mock.recorder = &MockLogoutServiceV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutServiceV2) EXPECT() *MockLogoutServiceV2MockRecorder {
	return m.recorder
}

// Logout mocks base method.
func (m *MockLogoutServiceV2) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockLogoutServiceV2MockRecorder) Logout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockLogoutServiceV2)(nil).Logout), ctx)
}
