// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources (interfaces: Config)
//
// Generated by this command:
//
//	mockgen -destination=mock_config_test.go -package=resources github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources Config
//

// Package resources is a generated GoMock package.
package resources

import (
	reflect "reflect"

	config "github.com/vskurikhin/DayBook3/auth/v2/internal/server/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
	isgomock struct{}
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// JWThs256SignKey mocks base method.
func (m *MockConfig) JWThs256SignKey(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "JWThs256SignKey", arg0)
}

// JWThs256SignKey indicates an expected call of JWThs256SignKey.
func (mr *MockConfigMockRecorder) JWThs256SignKey(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWThs256SignKey", reflect.TypeOf((*MockConfig)(nil).JWThs256SignKey), arg0)
}

// Values mocks base method.
func (m *MockConfig) Values() config.Values {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Values")
	ret0, _ := ret[0].(config.Values)
	return ret0
}

// Values indicates an expected call of Values.
func (mr *MockConfigMockRecorder) Values() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Values", reflect.TypeOf((*MockConfig)(nil).Values))
}
