// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources (interfaces: AuthServiceV2)
//
// Generated by this command:
//
//	mockgen -destination=mock_auth_service_v2_test.go -package=resources github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources AuthServiceV2
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	model "github.com/vskurikhin/DayBook3/auth/v2/internal/server/services/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceV2 is a mock of AuthServiceV2 interface.
type MockAuthServiceV2 struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceV2MockRecorder
	isgomock struct{}
}

// MockAuthServiceV2MockRecorder is the mock recorder for MockAuthServiceV2.
type MockAuthServiceV2MockRecorder struct {
	mock *MockAuthServiceV2
}

// NewMockAuthServiceV2 creates a new mock instance.
func NewMockAuthServiceV2(ctrl *gomock.Controller) *MockAuthServiceV2 {
	mock := &MockAuthServiceV2{ctrl: ctrl}
	mock.recorder = &MockAuthServiceV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceV2) EXPECT() *MockAuthServiceV2MockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockAuthServiceV2) Auth(ctx context.Context, login model.Login) (model.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx, login)
	ret0, _ := ret[0].(model.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockAuthServiceV2MockRecorder) Auth(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockAuthServiceV2)(nil).Auth), ctx, login)
}
