// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources (interfaces: OkServiceV2)
//
// Generated by this command:
//
//	mockgen -destination=mock_ok_service_v2_test.go -package=resources github.com/vskurikhin/DayBook3/auth/v2/internal/server/resources OkServiceV2
//

// Package resources is a generated GoMock package.
package resources

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOkServiceV2 is a mock of OkServiceV2 interface.
type MockOkServiceV2 struct {
	ctrl     *gomock.Controller
	recorder *MockOkServiceV2MockRecorder
	isgomock struct{}
}

// MockOkServiceV2MockRecorder is the mock recorder for MockOkServiceV2.
type MockOkServiceV2MockRecorder struct {
	mock *MockOkServiceV2
}

// NewMockOkServiceV2 creates a new mock instance.
func NewMockOkServiceV2(ctrl *gomock.Controller) *MockOkServiceV2 {
	mock := &MockOkServiceV2{ctrl: ctrl}
	mock.recorder = &MockOkServiceV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOkServiceV2) EXPECT() *MockOkServiceV2MockRecorder {
	return m.recorder
}

// Ok mocks base method.
func (m *MockOkServiceV2) Ok() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ok")
	ret0, _ := ret[0].(string)
	return ret0
}

// Ok indicates an expected call of Ok.
func (mr *MockOkServiceV2MockRecorder) Ok() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ok", reflect.TypeOf((*MockOkServiceV2)(nil).Ok))
}
