// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_attrs

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserAttr struct {
	UserName    string           `json:"user_name"`
	Attrs       []byte           `json:"attrs"`
	Name        string           `json:"name"`
	CreateTime  pgtype.Timestamp `json:"create_time"`
	UpdateTime  pgtype.Timestamp `json:"update_time"`
	Enabled     bool             `json:"enabled"`
	LocalChange bool             `json:"local_change"`
	Visible     bool             `json:"visible"`
	Flags       int32            `json:"flags"`
}
