// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_user_attrs.sql

package user_attrs

import (
	"context"
)

const createUserAttrs = `-- name: CreateUserAttrs :one
INSERT INTO user_attrs (
    user_name, attrs, name, enabled, local_change
) VALUES (
  $1, $2, $3, true, true
)
RETURNING user_name, attrs, name, create_time, update_time, enabled, local_change, visible, flags
`

type CreateUserAttrsParams struct {
	UserName string `json:"user_name"`
	Attrs    []byte `json:"attrs"`
	Name     string `json:"name"`
}

func (q *Queries) CreateUserAttrs(ctx context.Context, arg CreateUserAttrsParams) (UserAttr, error) {
	row := q.db.QueryRow(ctx, createUserAttrs, arg.UserName, arg.Attrs, arg.Name)
	var i UserAttr
	err := row.Scan(
		&i.UserName,
		&i.Attrs,
		&i.Name,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Enabled,
		&i.LocalChange,
		&i.Visible,
		&i.Flags,
	)
	return i, err
}

const deleteUserAttrs = `-- name: DeleteUserAttrs :exec
DELETE FROM user_attrs
WHERE user_name = $1
`

func (q *Queries) DeleteUserAttrs(ctx context.Context, userName string) error {
	_, err := q.db.Exec(ctx, deleteUserAttrs, userName)
	return err
}

const getUserAttrs = `-- name: GetUserAttrs :one
SELECT user_name, attrs, name, create_time, update_time, enabled, local_change, visible, flags FROM user_attrs
WHERE user_name = $1 LIMIT 1
`

func (q *Queries) GetUserAttrs(ctx context.Context, userName string) (UserAttr, error) {
	row := q.db.QueryRow(ctx, getUserAttrs, userName)
	var i UserAttr
	err := row.Scan(
		&i.UserName,
		&i.Attrs,
		&i.Name,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Enabled,
		&i.LocalChange,
		&i.Visible,
		&i.Flags,
	)
	return i, err
}

const listUserAttrs = `-- name: ListUserAttrs :many
SELECT user_name, attrs, name, create_time, update_time, enabled, local_change, visible, flags FROM user_attrs
ORDER BY user_name
`

func (q *Queries) ListUserAttrs(ctx context.Context) ([]UserAttr, error) {
	rows, err := q.db.Query(ctx, listUserAttrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAttr
	for rows.Next() {
		var i UserAttr
		if err := rows.Scan(
			&i.UserName,
			&i.Attrs,
			&i.Name,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Enabled,
			&i.LocalChange,
			&i.Visible,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAttrs = `-- name: UpdateUserAttrs :exec
UPDATE user_attrs
  SET attrs = $2,
      name = $3,
      enabled = $4
WHERE user_name = $1
`

type UpdateUserAttrsParams struct {
	UserName string `json:"user_name"`
	Attrs    []byte `json:"attrs"`
	Name     string `json:"name"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) UpdateUserAttrs(ctx context.Context, arg UpdateUserAttrsParams) error {
	_, err := q.db.Exec(ctx, updateUserAttrs,
		arg.UserName,
		arg.Attrs,
		arg.Name,
		arg.Enabled,
	)
	return err
}
