// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_user_name.sql

package user_name

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var _ Repo = (*Queries)(nil)

type Repo interface {
	CreateUserName(ctx context.Context, arg CreateUserNameParams) (UserName, error)
	DeleteUserNameByID(ctx context.Context, id pgtype.UUID) error
	DeleteUserNameByName(ctx context.Context, userName string) error
	GetUserName(ctx context.Context, userName string) (UserName, error)
	ListUserNames(ctx context.Context) ([]UserName, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	WithTx(tx pgx.Tx) *Queries
}
