// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_user_name.sql

package user_name

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserName = `-- name: CreateUserName :one
INSERT INTO user_name (
    user_name, password, enabled, local_change
) VALUES (
  $1, $2, true, true
)
RETURNING user_name, id, password, create_time, update_time, enabled, local_change, visible, flags
`

type CreateUserNameParams struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

func (q *Queries) CreateUserName(ctx context.Context, arg CreateUserNameParams) (UserName, error) {
	row := q.db.QueryRow(ctx, createUserName, arg.UserName, arg.Password)
	var i UserName
	err := row.Scan(
		&i.UserName,
		&i.ID,
		&i.Password,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Enabled,
		&i.LocalChange,
		&i.Visible,
		&i.Flags,
	)
	return i, err
}

const deleteUserNameByID = `-- name: DeleteUserNameByID :exec
DELETE FROM user_name
WHERE id = $1
`

func (q *Queries) DeleteUserNameByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserNameByID, id)
	return err
}

const deleteUserNameByName = `-- name: DeleteUserNameByName :exec
DELETE FROM user_name
WHERE user_name = $1
`

func (q *Queries) DeleteUserNameByName(ctx context.Context, userName string) error {
	_, err := q.db.Exec(ctx, deleteUserNameByName, userName)
	return err
}

const getUserName = `-- name: GetUserName :one
SELECT user_name, id, password, create_time, update_time, enabled, local_change, visible, flags FROM user_name
WHERE user_name = $1 LIMIT 1
`

func (q *Queries) GetUserName(ctx context.Context, userName string) (UserName, error) {
	row := q.db.QueryRow(ctx, getUserName, userName)
	var i UserName
	err := row.Scan(
		&i.UserName,
		&i.ID,
		&i.Password,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Enabled,
		&i.LocalChange,
		&i.Visible,
		&i.Flags,
	)
	return i, err
}

const listUserNames = `-- name: ListUserNames :many
SELECT user_name, id, password, create_time, update_time, enabled, local_change, visible, flags FROM user_name
ORDER BY user_name
`

func (q *Queries) ListUserNames(ctx context.Context) ([]UserName, error) {
	rows, err := q.db.Query(ctx, listUserNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserName
	for rows.Next() {
		var i UserName
		if err := rows.Scan(
			&i.UserName,
			&i.ID,
			&i.Password,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Enabled,
			&i.LocalChange,
			&i.Visible,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE user_name
  SET password = $2,
      enabled = $3
WHERE user_name = $1
`

type UpdateUserNameParams struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.UserName, arg.Password, arg.Enabled)
	return err
}
