pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id "${quarkusPluginId}" version "${quarkusPluginVersion}"
    }
}
include 'lib'
project(':lib').projectDir = new File('../lib')
include 'spi-mapstruct'
project(':spi-mapstruct').projectDir = new File('../spi-mapstruct')
rootProject.name = 'DayBook3'
